version: '3.8'
services:
  dicom-images-backend:
    container_name: dicom-back
    build:
      context: ./dicom-images-backend
      dockerfile: Dockerfile
    volumes:
      - ./dicom-images-backend:/app
    ports:
      - "${BACKEND_PORT}:8000"
    # entrypoint: ["/app/wait-for-db.sh"]
    command: >
      sh -c "python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - dicom-images-db
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  dicom-images-frontend:
    container_name: dicom-front
    build:
      context: ./dicom-images-frontend
      dockerfile: Dockerfile
    volumes:
      - ./dicom-images-frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      -  dicom-images-backend

  dicom-images-db:
    container_name: django-dicom-images-db
    image: mysql:5.7.22
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes: 
      - .dbdata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf 
    ports:
      - ${DB_PORT}:3306