# Generated by Django 4.1 on 2025-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_dicomfile_patient_birth_date_dicomfile_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
