version: '3.8'
services:
  dicom-images-backend:
    container_name: dicom-back
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    entrypoint: ["/app/wait-for-db.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - dicom-images-db

  dicom-images-db:
    container_name: django-dicom-images-db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: dicom_db
      MYSQL_USER: root
      # MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
